name: 'Code freeze'

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Type of release
        options:
          - major
          - minor

jobs:
  code-freeze:
    uses: NVIDIA/NeMo-FW-CI-templates/.github/workflows/_code_freeze.yml@v0.12.0
    with:
      library-name: NeMo Curator
      python-package: nemo_curator
      release-type: ${{ inputs.release-type }}

    secrets:
      SLACK_RELEASE_ENDPOINT: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
